# Generated by Django 4.0.3 on 2022-03-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Sex', models.CharField(max_length=255, verbose_name='Sex')),
                ('Age', models.CharField(max_length=255, verbose_name='Age')),
                ('Height', models.CharField(max_length=255, verbose_name='Height')),
                ('Weight', models.CharField(max_length=255, verbose_name='Weight')),
                ('Team', models.CharField(max_length=255, verbose_name='Team')),
                ('NOC', models.CharField(max_length=255, verbose_name='NOC')),
                ('Games', models.CharField(max_length=255, verbose_name='Games')),
                ('Year', models.IntegerField(verbose_name='Year')),
                ('Season', models.CharField(max_length=255, verbose_name='Season')),
                ('City', models.CharField(max_length=255, verbose_name='City')),
                ('Sport', models.CharField(max_length=255, verbose_name='Sport')),
                ('Event', models.CharField(max_length=255, verbose_name='Event')),
                ('Medal', models.CharField(max_length=255, verbose_name='Medal')),
            ],
        ),
    ]
