# Generated by Django 4.0.3 on 2022-03-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletes',
            name='ID',
        ),
    ]
