# Generated by Django 4.0.3 on 2022-03-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='Age',
            field=models.CharField(max_length=255, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='Height',
            field=models.CharField(max_length=255, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='Weight',
            field=models.CharField(max_length=255, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='Year',
            field=models.CharField(max_length=255, verbose_name='Year'),
        ),
    ]
