# Generated by Django 4.0.3 on 2022-03-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOC', models.CharField(max_length=255, verbose_name='NOC')),
                ('Region', models.CharField(max_length=255, verbose_name='Region')),
                ('Notes', models.CharField(max_length=255, verbose_name='Notes')),
            ],
        ),
    ]
